In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.cuda.is_available())
print(torch.__version__)

True
2.0.0


Introduction to tensors
##### Create tensor
Pytorch tensors are created using the torch.tensor() function. The function takes in a list or a numpy array as an argument and returns a tensor.
https://pytorch.org/docs/stable/tensors.html

In [3]:
# Scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [4]:
print(scalar.ndim)

0


In [5]:
# Get tensor back as python int
print(scalar.item())

7


In [6]:
# Vector
vector = torch.tensor([7, 7])
print(vector)


tensor([7, 7])


In [7]:
print(vector.ndim)

1


In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([ [7, 8], 
                        [9, 10]
                    ])
print(MATRIX)

tensor([[ 7,  8],
        [ 9, 10]])


In [10]:
print(MATRIX.ndim)

2


In [11]:
print(MATRIX[1])

tensor([ 9, 10])


In [12]:
print(MATRIX.shape) # return in form of tuple (row, column)

torch.Size([2, 2])


In [13]:
# TENSORS
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                    ])
print(TENSOR)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])


In [14]:
print(TENSOR.ndim)

3


In [15]:
print(TENSOR.shape) # return in form of tuple (dimention, row, column)

torch.Size([1, 3, 3])


In [16]:
print(TENSOR[0])

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])


#### Random tensors
Random tensors are important because the way many neural network learn is that they start with tensors full or random numbers and then adjust those random numbers to better represent the data. <br>
- Start with random numbers -> look at data -> update random number -> look at data -> update random number <br>
More information: https://pytorch.org/docs/stable/generated/torch.rand.html

In [17]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4) # 3 row and 4 column
print(random_tensor)

tensor([[0.0128, 0.7854, 0.7165, 0.2577],
        [0.4614, 0.9045, 0.0885, 0.9873],
        [0.4832, 0.9418, 0.9813, 0.8554]])


In [18]:
random_tensor.ndim

2

In [19]:
random_tensor_1layer = torch.rand(1, 3, 4) # 1 dimention, 10 row and 10 column
print(random_tensor_1layer)

tensor([[[0.3553, 0.8844, 0.4640, 0.8409],
         [0.8257, 0.0950, 0.1128, 0.9298],
         [0.0567, 0.8904, 0.0718, 0.3120]]])


In [20]:
random_tensor_1layer.ndim

3

In [21]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3, 224, 224)) # color channel, height, width 
print(f'size = {random_image_size_tensor.shape}\nndim = {random_image_size_tensor.ndim}')

size = torch.Size([3, 224, 224])
ndim = 3


In [22]:
print(random_image_size_tensor)

tensor([[[0.5910, 0.2583, 0.5204,  ..., 0.4454, 0.5235, 0.4857],
         [0.1402, 0.3633, 0.3348,  ..., 0.7120, 0.8702, 0.4211],
         [0.4363, 0.1724, 0.3786,  ..., 0.3114, 0.1724, 0.8996],
         ...,
         [0.6166, 0.9127, 0.0605,  ..., 0.9300, 0.3148, 0.6562],
         [0.8398, 0.0482, 0.9968,  ..., 0.0814, 0.5529, 0.9260],
         [0.7176, 0.9632, 0.5359,  ..., 0.1617, 0.4913, 0.1509]],

        [[0.6137, 0.8069, 0.4674,  ..., 0.0912, 0.1208, 0.2965],
         [0.3603, 0.0148, 0.8049,  ..., 0.0320, 0.3813, 0.5171],
         [0.1546, 0.9404, 0.5848,  ..., 0.0215, 0.7128, 0.7474],
         ...,
         [0.9727, 0.7810, 0.2449,  ..., 0.3177, 0.6892, 0.2667],
         [0.4317, 0.7130, 0.0015,  ..., 0.2283, 0.2103, 0.8492],
         [0.3180, 0.7136, 0.9232,  ..., 0.1978, 0.4647, 0.3650]],

        [[0.6633, 0.0568, 0.1315,  ..., 0.9706, 0.5211, 0.4299],
         [0.5167, 0.7744, 0.4099,  ..., 0.6661, 0.1388, 0.9068],
         [0.5337, 0.4803, 0.5090,  ..., 0.7182, 0.7275, 0.

### Zeros and Ones tensors

In [23]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3, 4))
print(zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [24]:
print(zeros * random_tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [25]:
# Create tensor of all ones
ones = torch.ones(size = (3, 4))
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [26]:
print(ones.dtype)

torch.float32


In [27]:
print(random_tensor.dtype)

torch.float32


### Crating a range of tensors and tensors-like

In [28]:
# user torch.range() and get deprecated message, user torch.arange() instead
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
print(one_to_ten)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [29]:
# Creating tensor like (It's same with shape of another tensor)
ten_zeros = torch.zeros_like(input = one_to_ten)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tensor Datatypes
More : https://pytorch.org/docs/stable/tensors.html

**Note** Tensor datatypes is one of the big 3 errors you'll run into with Pytorch & Deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [30]:
# Float 32 tensor when dtype is not defined torch will use float 32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # It's datatype of tensor e.g. torch.float16, torch.float32, torch.float64 or etc.
                               device = None, # It's device of tensor e.g. None, 'cpu', 'cuda', 'cuda:0', 'cuda:1' or etc.
                               requires_grad = False) # It's for gradient calculation
print(float_32_tensor)

tensor([3., 6., 9.])


In [31]:
print(float_32_tensor.dtype)

torch.float32


In [32]:
# Change tensor type from float 32 to float 16
float_16_tensor = float_32_tensor.type(torch.float16)
print(float_16_tensor)

tensor([3., 6., 9.], dtype=torch.float16)


In [33]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [34]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
print(int_32_tensor)

tensor([3, 6, 9], dtype=torch.int32)


In [35]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors
- Tensor attributes
1. Tensors not right datatype - to do get datatype from a tensor, can use the tensor.dtype attribute
2. Tensors not right shape - to do get shape from a tensor, can use the tensor.shape attribute
3. Tensors not on the right device - to do get device from a tensor, can use the tensor.device attribute

In [36]:
# Create a tensor
some_tensor = torch.rand(3, 4)
print(some_tensor)

tensor([[0.2238, 0.6913, 0.9426, 0.4260],
        [0.5869, 0.7436, 0.1694, 0.1713],
        [0.4546, 0.2657, 0.6734, 0.0337]])


In [37]:
print(f'Size = {some_tensor.shape}\nShape = {some_tensor.shape}')

Size = torch.Size([3, 4])
Shape = torch.Size([3, 4])


In [38]:
# Find out detail about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is stored on: {some_tensor.device}')

tensor([[0.2238, 0.6913, 0.9426, 0.4260],
        [0.5869, 0.7436, 0.1694, 0.1713],
        [0.4546, 0.2657, 0.6734, 0.0337]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu


### Manipulating tensors ( tensor operations )

Tensor opreration include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division 
* Matrix multiplication

In [39]:
# Create a tensor  and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [40]:
# Multiply our tensor by 10
tensor * 10

tensor([10, 20, 30])

In [41]:
# Substract by 10
tensor - 10

tensor([-9, -8, -7])

In [42]:
# Try out PyTorch in-built function
torch.multiply(tensor, 10) # or torch.mul(tensor, 10)

tensor([10, 20, 30])

In [43]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication ( Dot product )

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **Inner dimensions** must match:
* `(3, 2) @ (3 , 2) ` won't work
* `(2, 3) @ (3 , 2) ` will work
* `(3, 2) @ (2 , 3) ` will work
2. The result matrix has the shape of the **Outer dimensions**:
* `(2, 3) @ (3, 2)` will result in a `(2, 2)` matrix
* `(3, 2) @ (2, 3)` will result in a `(3, 3)` matrix

Matrix multiplication application - http://matrixmultiplication.xyz/

In [44]:
# Element wise multiplication
print(tensor, '*', tensor)
print(f'Equal: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equal: tensor([1, 4, 9])


In [45]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [46]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [47]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 998 µs


In [48]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### One of the most common errors in deep learning: shape errors

In [49]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_A, tensor_B) # torch.mm it's same with torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

Matmul used for matrix multiplication that is not square e.g. 3x2 and 2x3 or 3x2 and 2x4 <br> ( row of first matrix must be equal to column of second matrix )

How to fixed shape errors, user **transpose()** method to transpose a matrix <br>
A transpose is when you flip a matrix along its diagonal ( turning rows into columns and vice versa )


In [50]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [51]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [52]:
# Try to used matmul with transpose
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [53]:
# Matrix multiplication
print(f'Original shape of tensor A: {tensor_A.shape}, tensor B: {tensor_B.shape}')
print(f'New shapes of tensor A: {tensor_A.shape}, tensor B.T: {tensor_B.T.shape}')
print(f'Multiply tensor A: {tensor_A.shape} by tensor B.T: {tensor_B.T.shape} <- Inner dimension must match \nusing torch.matmul:\n {torch.matmul(tensor_A, tensor_B.T)}\nOutput shape: {torch.matmul(tensor_A, tensor_B.T).shape}')

Original shape of tensor A: torch.Size([3, 2]), tensor B: torch.Size([3, 2])
New shapes of tensor A: torch.Size([3, 2]), tensor B.T: torch.Size([2, 3])
Multiply tensor A: torch.Size([3, 2]) by tensor B.T: torch.Size([2, 3]) <- Inner dimension must match 
using torch.matmul:
 tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc. (tensor aggregations)

In [54]:
# Create a tensor
x = torch.arange(1, 100, 10)
print(x)
print(x.dtype)

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])
torch.int64


In [55]:
# Find min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [56]:
# Find max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [57]:
# Find mean
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [58]:
# Find mean - Note: torch.mean() required tensor type to be float32
# Change type to float32
torch.mean(x.type(torch.float32))

tensor(46.)

In [59]:
# Convert type with argument
torch.mean(x, dtype = torch.float32)

tensor(46.)

In [60]:
x.type(torch.float32).mean()

tensor(46.)

## Finding the positional maximum and minimum

In [61]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [62]:
# Find the position of the minimum value with argmin() -> return index position of target minimum value
pos_min = x.argmin()

In [63]:
x[pos_min]

tensor(1)

In [64]:
# Find the position in tensor that has the maximum value with argmax() -> return index position of target maximum value
pos_max = x.argmax()
pos_max

tensor(9)

In [65]:
x[pos_max]

tensor(91)

## Reshapeing, stacking, squeezing, unsqueezing tensor
* Reshape - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shaoe but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeezing - Remove all `1` dimensions from a tensor
* Unsqueeze - Add a dimension of size `1` to a tensor
* Permute - Return a view of the input with dimension permuted (swapped) in a certain way

In [66]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [67]:
# Add extra dimension to tensor
x_reshape = x.reshape(1, 10) # .reshape(row, column)
x_reshape, x_reshape.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [68]:
# Change the view
z = x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [69]:
# Changing z changes x (because they are the same tensor)
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [70]:
# Stack tensors on top of each other
x_stack = torch.stack([x, x, x, x], dim = 0)
x_stack

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [71]:
x_stack_dim1 = torch.stack([x, x, x, x], dim = 1)
x_stack_dim1

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [72]:
# torch.squeeze() - removel all single dimentions from a target tensor
print(f'Previous shape: {x_reshape.shape}')
print(f'Previous data: {x_reshape}')
print('-' * 50)
x_reshape_squeeze = torch.squeeze(x_reshape)
print(f'New shape: {x_reshape_squeeze.shape}')
print(f'New data: {x_reshape_squeeze}')

Previous shape: torch.Size([1, 10])
Previous data: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
--------------------------------------------------
New shape: torch.Size([10])
New data: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [73]:
# torch.unsequeeze() - add a dimension of 1 to a target tensor at a specified dimention
print(f'Previous targe: {x_reshape_squeeze}')
print(f'Previous shape: {x_reshape_squeeze.shape}')

# Add extra dimension to tensor
print('-' * 50)
x_unsqueeze_dim0 = torch.unsqueeze(x_reshape_squeeze, dim = 0)
print(f'New target dim 0: {x_unsqueeze_dim0}')
print(f'New shape dim 0: {x_unsqueeze_dim0.shape}')
print('-' * 50)
x_unsqueeze_dim1 = torch.unsqueeze(x_reshape_squeeze, dim = 1)
print(f'New target dim 1: {x_unsqueeze_dim1}')
print(f'New shape dim 1: {x_unsqueeze_dim1.shape}')

Previous targe: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previous shape: torch.Size([10])
--------------------------------------------------
New target dim 0: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
New shape dim 0: torch.Size([1, 10])
--------------------------------------------------
New target dim 1: tensor([[ 5.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])
New shape dim 1: torch.Size([10, 1])


In [74]:
# Torch.permute() - rearrange the dimensions of a tensor (เรียงลำดับของมิติใหม่) 
x_original = torch.rand(size = (224, 224, 3))
print('-' * 50)
print(f'Before permuted: {x_original.shape}')

# Permute the original tensor to rearrange the dimensions
print('-' * 50)
x_permuted = x_original.permute(2, 0, 1)
print(f'Shape after permuted: {x_permuted.shape}')

--------------------------------------------------
Before permuted: torch.Size([224, 224, 3])
--------------------------------------------------
Shape after permuted: torch.Size([3, 224, 224])


### Indexing (selecting data from tensor) <br>
Indexing with PyTorch is similar to indexing with Python NumPy.

In [75]:
# Create a tensors
x = torch.arange(1, 19).reshape(2, 3, 3) # reshape(0th, 1st, 2nd) dimension
print(x, x.shape, sep = '\n')

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])
torch.Size([2, 3, 3])


In [76]:
# Let's index on our new tensor
print(f'First item in our tensor x: \n{x[0]}')

First item in our tensor x: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [77]:
# Let's index on the middle bracket (dim = 1)
print(x[0][0])
print(x[0, 0]) # It's same of x[0][0]

tensor([1, 2, 3])
tensor([1, 2, 3])


In [78]:
# Let's index on the most inner bracket (last dimension)
print(x[0][0][0])

tensor(1)


In [79]:
# You can also use ":" for select "all" of a target dimension
print(x[:, 0])

tensor([[ 1,  2,  3],
        [10, 11, 12]])


In [80]:
# Get all values of 0th and 1st dimensions but only index 1 of the 2nd dimension
print(x[:, :, 1])

tensor([[ 2,  5,  8],
        [11, 14, 17]])


In [81]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimensions
print(x[:, 1, 1])

tensor([ 5, 14])


In [82]:
# Get index 0 of 0th and 1st dimension and all value of 2nd dimension
print(x[0, 0, :])

tensor([1, 2, 3])


## PyTorch tensors & NumPy <br>
NumPy is a popular scientific Python numerical computing library. <br>
And because of this, PyTorch has functionality to interact with it. <br>
* Data in NumpPy, want in PyTorch tensor -> torch.from_numpy(ndarray)
* PyTorch tensor, want in NumPy -> Torch.Tensor.numpy()

In [83]:
# NumpPy array to tensor
import torch
import numpy as np

In [88]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning ! when converting from numpy to pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
print(f'Numpy array: {array}')
print(f'Torch tensor: {tensor}')

Numpy array: [1. 2. 3. 4. 5. 6. 7.]
Torch tensor: tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [89]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
print(f'Numpy array: {array}')
print(f'Torch tensor: {tensor}')

Numpy array: [2. 3. 4. 5. 6. 7. 8.]
Torch tensor: tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [91]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
print(f'Torch tensor: {tensor}')
print(f'Numpy array: {numpy_tensor}')

Torch tensor: tensor([1., 1., 1., 1., 1., 1., 1.])
Numpy array: [1. 1. 1. 1. 1. 1. 1.]


In [92]:
# Chage the tensor, what happend to the numpy array?
tensor = tensor + 1
print(f'Torch tensor: {tensor}')
print(f'Numpy array: {numpy_tensor}')

Torch tensor: tensor([2., 2., 2., 2., 2., 2., 2.])
Numpy array: [1. 1. 1. 1. 1. 1. 1.]


## Reproductibility in PyTorch (Trying to take random out of random)

In short how a neural network learns:

`Start with random numbers -> tensor operation -> update random number to try and make them better representations of the data -> again -> again -> again . . `

To reduce the randomness in neural networks and PyTorch comes the concepts of a **random seed** <br>
Essentially what the random seed does is "flavour" the randomness.

In [1]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(f'Random tensor A: \n{random_tensor_A}')
print(f'Random tensor B: \n{random_tensor_B}')
print(random_tensor_A == random_tensor_B)

Random tensor A: 
tensor([[0.1530, 0.6855, 0.3763, 0.4206],
        [0.5474, 0.6293, 0.2097, 0.3801],
        [0.8129, 0.4922, 0.2239, 0.2644]])
Random tensor B: 
tensor([[0.0706, 0.4151, 0.9352, 0.6690],
        [0.6119, 0.2744, 0.8854, 0.3508],
        [0.5313, 0.3817, 0.5076, 0.8583]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [2]:
# Let's make some random but reproducible tensors
torch.manual_seed(42)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(42)
random_tensor_D = torch.rand(3, 4)
print(f'Random tensor A: \n{random_tensor_C}')
print(f'Random tensor B: \n{random_tensor_D}')
print(random_tensor_C == random_tensor_D)

Random tensor A: 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Random tensor B: 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Runing tensors and PyTorch objects on the GPUs (and making faster computations)

In [11]:
# Checking GPU access with PyTorch
import torch
import numpy as np
print(torch.cuda.is_available())

True


In [12]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Using {device} device')

Using cuda device


In [13]:
# Count number or devices
torch.cuda.device_count()

1

# Putting tensors (models) on the GPUs
The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [14]:
# Create a tensor (default on CPU)
tensor_cpu = torch.tensor([1,2, 3], device = 'cpu')
# Tensor not on GPU
print(tensor_cpu, tensor_cpu.device)

tensor([1, 2, 3]) cpu


In [15]:
# Move tensor to GPU if available 
tensor_gpu = tensor_cpu.to(device=device)
print(tensor_gpu, tensor_gpu.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


### Move tensors back to CPU

In [16]:
# If tensor is on GPU, can't transform to numpy
tensor_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [18]:
# To fix the GPU tensor with NumPy issue, we can first set it to CPU then convert to numpy
tensor_back_to_cpu = tensor_gpu.cpu().numpy()
print(tensor_back_to_cpu, type(tensor_back_to_cpu))

[1 2 3] <class 'numpy.ndarray'>


### Exercises & Extra-curriculum

In [62]:
# Set seed
torch.manual_seed(0)
# Create a tensor
tensor_random = torch.rand(7, 7)
print(tensor_random)
random_another = torch.rand(1, 7)
print(random_another)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])


In [63]:
# matrix multiplication
tensor_result = torch.matmul(tensor_random, random_another.T)
print(tensor_result, '\n', tensor_result.shape)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) 
 torch.Size([7, 1])


In [66]:
## Note ! .to() method is used to move a tensor to a specified device
torch.manual_seed(1234)
tensor_random_gpu1 = torch.rand(2, 3).to(device = 'cuda')
tensor_random_gpu2 = torch.rand(2, 3).to(device = 'cuda')
print(tensor_random_gpu1, tensor_random_gpu2, sep = '\n')

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


In [67]:
torch_matrix_mul_result = torch.matmul(tensor_random_gpu1, tensor_random_gpu2.T)
print(torch_matrix_mul_result, torch_matrix_mul_result.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


In [69]:
max_value = torch.max(torch_matrix_mul_result)
print(max_value)
min_value = torch.min(torch_matrix_mul_result)
print(min_value)
pos_max = torch.argmax(torch_matrix_mul_result)
print(pos_max)
pos_min = torch.argmin(torch_matrix_mul_result)
print(pos_min)

tensor(0.5617, device='cuda:0')
tensor(0.3647, device='cuda:0')
tensor(3, device='cuda:0')
tensor(0, device='cuda:0')


In [84]:
torch.manual_seed(7)
tensor_random  = torch.rand(1, 1, 1, 10)
print(tensor_random)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])


In [87]:
# tensor_sequeeze = torch.squeeze(tensor_random, (0, 1, 2)) # 0, 1, 2 are the dimensions to be removed
tensor_sequeeze = tensor_random.squeeze()
print(tensor_random, tensor_random.size())
print(tensor_sequeeze, tensor_sequeeze.size())

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
