In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
print(torch.cuda.is_available())
print(torch.__version__)

True
2.0.0


Introduction to tensors
##### Create tensor
Pytorch tensors are created using the torch.tensor() function. The function takes in a list or a numpy array as an argument and returns a tensor.
https://pytorch.org/docs/stable/tensors.html

In [7]:
# Scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [8]:
print(scalar.ndim)

0


In [9]:
# Get tensor back as python int
print(scalar.item())

7


In [10]:
# Vector
vector = torch.tensor([7, 7])
print(vector)


tensor([7, 7])


In [11]:
print(vector.ndim)

1


In [12]:
vector.shape

torch.Size([2])

In [21]:
# Matrix
MATRIX = torch.tensor([ [7, 8], 
                        [9, 10]
                    ])
print(MATRIX)

tensor([[ 7,  8],
        [ 9, 10]])


In [22]:
print(MATRIX.ndim)

2


In [23]:
print(MATRIX[1])

tensor([ 9, 10])


In [24]:
print(MATRIX.shape) # return in form of tuple (row, column)

torch.Size([2, 2])


In [36]:
# TENSORS
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                    ])
print(TENSOR)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])


In [37]:
print(TENSOR.ndim)

3


In [38]:
print(TENSOR.shape) # return in form of tuple (dimention, row, column)

torch.Size([1, 3, 3])


In [39]:
print(TENSOR[0])

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])
