In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.cuda.is_available())
print(torch.__version__)

True
2.0.0


Introduction to tensors
##### Create tensor
Pytorch tensors are created using the torch.tensor() function. The function takes in a list or a numpy array as an argument and returns a tensor.
https://pytorch.org/docs/stable/tensors.html

In [3]:
# Scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [4]:
print(scalar.ndim)

0


In [5]:
# Get tensor back as python int
print(scalar.item())

7


In [6]:
# Vector
vector = torch.tensor([7, 7])
print(vector)


tensor([7, 7])


In [7]:
print(vector.ndim)

1


In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([ [7, 8], 
                        [9, 10]
                    ])
print(MATRIX)

tensor([[ 7,  8],
        [ 9, 10]])


In [10]:
print(MATRIX.ndim)

2


In [11]:
print(MATRIX[1])

tensor([ 9, 10])


In [12]:
print(MATRIX.shape) # return in form of tuple (row, column)

torch.Size([2, 2])


In [13]:
# TENSORS
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                    ])
print(TENSOR)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])


In [14]:
print(TENSOR.ndim)

3


In [15]:
print(TENSOR.shape) # return in form of tuple (dimention, row, column)

torch.Size([1, 3, 3])


In [16]:
print(TENSOR[0])

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])


#### Random tensors
Random tensors are important because the way many neural network learn is that they start with tensors full or random numbers and then adjust those random numbers to better represent the data. <br>
- Start with random numbers -> look at data -> update random number -> look at data -> update random number <br>
More information: https://pytorch.org/docs/stable/generated/torch.rand.html

In [17]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4) # 3 row and 4 column
print(random_tensor)

tensor([[0.4294, 0.6940, 0.0527, 0.6931],
        [0.4862, 0.0033, 0.9077, 0.2464],
        [0.0805, 0.0971, 0.7182, 0.9715]])


In [18]:
random_tensor.ndim

2

In [19]:
random_tensor_1layer = torch.rand(1, 3, 4) # 1 dimention, 10 row and 10 column
print(random_tensor_1layer)

tensor([[[0.7991, 0.7643, 0.6201, 0.0871],
         [0.8395, 0.3065, 0.2383, 0.8476],
         [0.6370, 0.5198, 0.4049, 0.3528]]])


In [20]:
random_tensor_1layer.ndim

3

In [21]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3, 224, 224)) # color channel, height, width 
print(f'size = {random_image_size_tensor.shape}\nndim = {random_image_size_tensor.ndim}')

size = torch.Size([3, 224, 224])
ndim = 3


In [22]:
print(random_image_size_tensor)

tensor([[[0.7964, 0.9421, 0.1174,  ..., 0.4701, 0.1389, 0.8391],
         [0.3628, 0.9491, 0.6383,  ..., 0.2325, 0.9933, 0.2838],
         [0.8736, 0.0744, 0.1076,  ..., 0.0230, 0.6848, 0.8941],
         ...,
         [0.8579, 0.9981, 0.1081,  ..., 0.0124, 0.2863, 0.8551],
         [0.8776, 0.4989, 0.4219,  ..., 0.8609, 0.8670, 0.5160],
         [0.8388, 0.0276, 0.4270,  ..., 0.5940, 0.8487, 0.4371]],

        [[0.6842, 0.8410, 0.0984,  ..., 0.4229, 0.0849, 0.6793],
         [0.0402, 0.2554, 0.9929,  ..., 0.3695, 0.5535, 0.6693],
         [0.4035, 0.4436, 0.4083,  ..., 0.3745, 0.0293, 0.5549],
         ...,
         [0.6538, 0.0465, 0.3703,  ..., 0.1409, 0.8012, 0.2369],
         [0.7192, 0.7448, 0.9499,  ..., 0.4241, 0.8721, 0.7141],
         [0.6097, 0.7328, 0.2658,  ..., 0.8372, 0.3257, 0.8427]],

        [[0.6256, 0.2394, 0.3300,  ..., 0.7037, 0.2755, 0.9942],
         [0.2342, 0.7096, 0.1428,  ..., 0.7860, 0.0289, 0.8363],
         [0.4500, 0.6355, 0.6874,  ..., 0.4825, 0.4941, 0.

### Zeros and Ones tensors

In [23]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3, 4))
print(zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [24]:
print(zeros * random_tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [25]:
# Create tensor of all ones
ones = torch.ones(size = (3, 4))
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [26]:
print(ones.dtype)

torch.float32


In [27]:
print(random_tensor.dtype)

torch.float32


### Crating a range of tensors and tensors-like

In [28]:
# user torch.range() and get deprecated message, user torch.arange() instead
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
print(one_to_ten)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [29]:
# Creating tensor like (It's same with shape of another tensor)
ten_zeros = torch.zeros_like(input = one_to_ten)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tensor Datatypes
More : https://pytorch.org/docs/stable/tensors.html

**Note** Tensor datatypes is one of the big 3 errors you'll run into with Pytorch & Deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [30]:
# Float 32 tensor when dtype is not defined torch will use float 32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # It's datatype of tensor e.g. torch.float16, torch.float32, torch.float64 or etc.
                               device = None, # It's device of tensor e.g. None, 'cpu', 'cuda', 'cuda:0', 'cuda:1' or etc.
                               requires_grad = False) # It's for gradient calculation
print(float_32_tensor)

tensor([3., 6., 9.])


In [31]:
print(float_32_tensor.dtype)

torch.float32


In [32]:
# Change tensor type from float 32 to float 16
float_16_tensor = float_32_tensor.type(torch.float16)
print(float_16_tensor)

tensor([3., 6., 9.], dtype=torch.float16)


In [33]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [34]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
print(int_32_tensor)

tensor([3, 6, 9], dtype=torch.int32)


In [35]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors
- Tensor attributes
1. Tensors not right datatype - to do get datatype from a tensor, can use the tensor.dtype attribute
2. Tensors not right shape - to do get shape from a tensor, can use the tensor.shape attribute
3. Tensors not on the right device - to do get device from a tensor, can use the tensor.device attribute

In [36]:
# Create a tensor
some_tensor = torch.rand(3, 4)
print(some_tensor)

tensor([[0.0779, 0.6420, 0.9785, 0.5419],
        [0.2550, 0.8252, 0.1584, 0.8206],
        [0.9976, 0.2078, 0.3301, 0.1322]])


In [37]:
print(f'Size = {some_tensor.shape}\nShape = {some_tensor.shape}')

Size = torch.Size([3, 4])
Shape = torch.Size([3, 4])


In [38]:
# Find out detail about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is stored on: {some_tensor.device}')

tensor([[0.0779, 0.6420, 0.9785, 0.5419],
        [0.2550, 0.8252, 0.1584, 0.8206],
        [0.9976, 0.2078, 0.3301, 0.1322]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu


### Manipulating tensors ( tensor operations )

Tensor opreration include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division 
* Matrix multiplication

In [39]:
# Create a tensor  and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [40]:
# Multiply our tensor by 10
tensor * 10

tensor([10, 20, 30])

In [41]:
# Substract by 10
tensor - 10

tensor([-9, -8, -7])

In [42]:
# Try out PyTorch in-built function
torch.multiply(tensor, 10) # or torch.mul(tensor, 10)

tensor([10, 20, 30])

In [43]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication ( Dot product )

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **Inner dimensions** must match:
* `(3, 2) @ (3 , 2) ` won't work
* `(2, 3) @ (3 , 2) ` will work
* `(3, 2) @ (2 , 3) ` will work
2. The result matrix has the shape of the **Outer dimensions**:
* `(2, 3) @ (3, 2)` will result in a `(2, 2)` matrix
* `(3, 2) @ (2, 3)` will result in a `(3, 3)` matrix

Matrix multiplication application - http://matrixmultiplication.xyz/

In [44]:
# Element wise multiplication
print(tensor, '*', tensor)
print(f'Equal: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equal: tensor([1, 4, 9])


In [45]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [46]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [47]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 1 ms


In [48]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### One of the most common errors in deep learning: shape errors

In [49]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_A, tensor_B) # torch.mm it's same with torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

Matmul used for matrix multiplication that is not square e.g. 3x2 and 2x3 or 3x2 and 2x4 <br> ( row of first matrix must be equal to column of second matrix )

How to fixed shape errors, user **transpose()** method to transpose a matrix <br>
A transpose is when you flip a matrix along its diagonal ( turning rows into columns and vice versa )


In [50]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [51]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [52]:
# Try to used matmul with transpose
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])