In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.cuda.is_available())
print(torch.__version__)

True
2.0.0


Introduction to tensors
##### Create tensor
Pytorch tensors are created using the torch.tensor() function. The function takes in a list or a numpy array as an argument and returns a tensor.
https://pytorch.org/docs/stable/tensors.html

In [3]:
# Scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [4]:
print(scalar.ndim)

0


In [5]:
# Get tensor back as python int
print(scalar.item())

7


In [6]:
# Vector
vector = torch.tensor([7, 7])
print(vector)


tensor([7, 7])


In [7]:
print(vector.ndim)

1


In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([ [7, 8], 
                        [9, 10]
                    ])
print(MATRIX)

tensor([[ 7,  8],
        [ 9, 10]])


In [10]:
print(MATRIX.ndim)

2


In [11]:
print(MATRIX[1])

tensor([ 9, 10])


In [12]:
print(MATRIX.shape) # return in form of tuple (row, column)

torch.Size([2, 2])


In [13]:
# TENSORS
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]],
                    ])
print(TENSOR)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])


In [14]:
print(TENSOR.ndim)

3


In [15]:
print(TENSOR.shape) # return in form of tuple (dimention, row, column)

torch.Size([1, 3, 3])


In [16]:
print(TENSOR[0])

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])


#### Random tensors
Random tensors are important because the way many neural network learn is that they start with tensors full or random numbers and then adjust those random numbers to better represent the data. <br>
- Start with random numbers -> look at data -> update random number -> look at data -> update random number <br>
More information: https://pytorch.org/docs/stable/generated/torch.rand.html

In [17]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4) # 3 row and 4 column
print(random_tensor)

tensor([[0.2688, 0.2712, 0.7989, 0.9862],
        [0.9316, 0.4902, 0.4397, 0.6886],
        [0.6680, 0.3841, 0.8422, 0.9646]])


In [18]:
random_tensor.ndim

2

In [19]:
random_tensor_1layer = torch.rand(1, 3, 4) # 1 dimention, 10 row and 10 column
print(random_tensor_1layer)

tensor([[[0.2447, 0.2477, 0.6710, 0.7023],
         [0.7149, 0.8574, 0.7837, 0.8024],
         [0.2169, 0.3534, 0.6551, 0.3873]]])


In [20]:
random_tensor_1layer.ndim

3

In [21]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3, 224, 224)) # color channel, height, width 
print(f'size = {random_image_size_tensor.shape}\nndim = {random_image_size_tensor.ndim}')

size = torch.Size([3, 224, 224])
ndim = 3


In [22]:
print(random_image_size_tensor)

tensor([[[1.8668e-01, 1.1703e-01, 1.0429e-01,  ..., 9.2669e-03,
          2.2852e-02, 8.8340e-03],
         [2.3027e-01, 5.8563e-01, 8.1845e-01,  ..., 7.3647e-01,
          3.4354e-01, 7.3355e-01],
         [5.3588e-01, 5.0543e-01, 1.5194e-01,  ..., 1.0987e-01,
          3.2724e-02, 1.2093e-01],
         ...,
         [4.6225e-01, 7.0444e-01, 8.2234e-01,  ..., 2.6870e-01,
          7.2857e-01, 5.7405e-01],
         [4.8563e-01, 4.9893e-01, 9.1233e-01,  ..., 3.4154e-01,
          4.1472e-01, 4.2365e-01],
         [1.8233e-01, 8.8653e-01, 3.1222e-02,  ..., 7.3121e-02,
          6.0412e-01, 4.6560e-01]],

        [[5.1391e-01, 1.7995e-02, 4.2825e-01,  ..., 9.9192e-01,
          6.4373e-06, 9.7091e-01],
         [4.4730e-01, 9.1487e-01, 8.4765e-01,  ..., 9.8809e-01,
          7.8685e-01, 1.6224e-01],
         [6.2120e-01, 3.6787e-01, 8.3706e-01,  ..., 6.3709e-01,
          5.0654e-01, 3.3624e-02],
         ...,
         [3.5694e-01, 4.0491e-02, 9.6749e-01,  ..., 5.3535e-01,
          4.334

### Zeros and Ones tensors

In [23]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3, 4))
print(zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [24]:
print(zeros * random_tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [25]:
# Create tensor of all ones
ones = torch.ones(size = (3, 4))
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [26]:
print(ones.dtype)

torch.float32


In [27]:
print(random_tensor.dtype)

torch.float32


### Crating a range of tensors and tensors-like

In [28]:
# user torch.range() and get deprecated message, user torch.arange() instead
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
print(one_to_ten)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [29]:
# Creating tensor like (It's same with shape of another tensor)
ten_zeros = torch.zeros_like(input = one_to_ten)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tensor Datatypes
More : https://pytorch.org/docs/stable/tensors.html

**Note** Tensor datatypes is one of the big 3 errors you'll run into with Pytorch & Deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [30]:
# Float 32 tensor when dtype is not defined torch will use float 32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # It's datatype of tensor e.g. torch.float16, torch.float32, torch.float64 or etc.
                               device = None, # It's device of tensor e.g. None, 'cpu', 'cuda', 'cuda:0', 'cuda:1' or etc.
                               requires_grad = False) # It's for gradient calculation
print(float_32_tensor)

tensor([3., 6., 9.])


In [31]:
print(float_32_tensor.dtype)

torch.float32


In [32]:
# Change tensor type from float 32 to float 16
float_16_tensor = float_32_tensor.type(torch.float16)
print(float_16_tensor)

tensor([3., 6., 9.], dtype=torch.float16)


In [33]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [34]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
print(int_32_tensor)

tensor([3, 6, 9], dtype=torch.int32)


In [35]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors
- Tensor attributes
1. Tensors not right datatype - to do get datatype from a tensor, can use the tensor.dtype attribute
2. Tensors not right shape - to do get shape from a tensor, can use the tensor.shape attribute
3. Tensors not on the right device - to do get device from a tensor, can use the tensor.device attribute

In [36]:
# Create a tensor
some_tensor = torch.rand(3, 4)
print(some_tensor)

tensor([[0.6872, 0.6345, 0.3939, 0.4676],
        [0.3886, 0.2229, 0.6893, 0.7023],
        [0.3538, 0.8364, 0.1184, 0.2214]])


In [37]:
print(f'Size = {some_tensor.shape}\nShape = {some_tensor.shape}')

Size = torch.Size([3, 4])
Shape = torch.Size([3, 4])


In [38]:
# Find out detail about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is stored on: {some_tensor.device}')

tensor([[0.6872, 0.6345, 0.3939, 0.4676],
        [0.3886, 0.2229, 0.6893, 0.7023],
        [0.3538, 0.8364, 0.1184, 0.2214]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu


### Manipulating tensors ( tensor operations )

Tensor opreration include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division 
* Matrix multiplication

In [39]:
# Create a tensor  and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [40]:
# Multiply our tensor by 10
tensor * 10

tensor([10, 20, 30])

In [41]:
# Substract by 10
tensor - 10

tensor([-9, -8, -7])

In [42]:
# Try out PyTorch in-built function
torch.multiply(tensor, 10) # or torch.mul(tensor, 10)

tensor([10, 20, 30])

In [43]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication ( Dot product )

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **Inner dimensions** must match:
* `(3, 2) @ (3 , 2) ` won't work
* `(2, 3) @ (3 , 2) ` will work
* `(3, 2) @ (2 , 3) ` will work
2. The result matrix has the shape of the **Outer dimensions**:
* `(2, 3) @ (3, 2)` will result in a `(2, 2)` matrix
* `(3, 2) @ (2, 3)` will result in a `(3, 3)` matrix

Matrix multiplication application - http://matrixmultiplication.xyz/

In [44]:
# Element wise multiplication
print(tensor, '*', tensor)
print(f'Equal: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equal: tensor([1, 4, 9])


In [45]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [46]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

In [47]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 1.51 ms


In [48]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 1.01 ms


tensor(14)

### One of the most common errors in deep learning: shape errors

In [49]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
torch.mm(tensor_A, tensor_B) # torch.mm it's same with torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

Matmul used for matrix multiplication that is not square e.g. 3x2 and 2x3 or 3x2 and 2x4 <br> ( row of first matrix must be equal to column of second matrix )

How to fixed shape errors, user **transpose()** method to transpose a matrix <br>
A transpose is when you flip a matrix along its diagonal ( turning rows into columns and vice versa )


In [50]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [51]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [52]:
# Try to used matmul with transpose
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [53]:
# Matrix multiplication
print(f'Original shape of tensor A: {tensor_A.shape}, tensor B: {tensor_B.shape}')
print(f'New shapes of tensor A: {tensor_A.shape}, tensor B.T: {tensor_B.T.shape}')
print(f'Multiply tensor A: {tensor_A.shape} by tensor B.T: {tensor_B.T.shape} <- Inner dimension must match \nusing torch.matmul:\n {torch.matmul(tensor_A, tensor_B.T)}\nOutput shape: {torch.matmul(tensor_A, tensor_B.T).shape}')

Original shape of tensor A: torch.Size([3, 2]), tensor B: torch.Size([3, 2])
New shapes of tensor A: torch.Size([3, 2]), tensor B.T: torch.Size([2, 3])
Multiply tensor A: torch.Size([3, 2]) by tensor B.T: torch.Size([2, 3]) <- Inner dimension must match 
using torch.matmul:
 tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc. (tensor aggregations)

In [54]:
# Create a tensor
x = torch.arange(1, 100, 10)
print(x)
print(x.dtype)

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])
torch.int64


In [55]:
# Find min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [56]:
# Find max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [57]:
# Find mean
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [58]:
# Find mean - Note: torch.mean() required tensor type to be float32
# Change type to float32
torch.mean(x.type(torch.float32))

tensor(46.)

In [59]:
# Convert type with argument
torch.mean(x, dtype = torch.float32)

tensor(46.)

In [60]:
x.type(torch.float32).mean()

tensor(46.)

## Finding the positional maximum and minimum

In [61]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [62]:
# Find the position of the minimum value with argmin() -> return index position of target minimum value
pos_min = x.argmin()

In [63]:
x[pos_min]

tensor(1)

In [64]:
# Find the position in tensor that has the maximum value with argmax() -> return index position of target maximum value
pos_max = x.argmax()
pos_max

tensor(9)

In [65]:
x[pos_max]

tensor(91)

## Reshapeing, stacking, squeezing, unsqueezing tensor
* Reshape - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shaoe but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeezing - Remove all `1` dimensions from a tensor
* Unsqueeze - Add a dimension of size `1` to a tensor
* Permute - Return a view of the input with dimension permuted (swapped) in a certain way

In [80]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [81]:
# Add extra dimension to tensor
x_reshape = x.reshape(1, 10) # .reshape(row, column)
x_reshape, x_reshape.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [82]:
# Change the view
z = x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [83]:
# Changing z changes x (because they are the same tensor)
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [84]:
# Stack tensors on top of each other
x_stack = torch.stack([x, x, x, x], dim = 0)
x_stack

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [85]:
x_stack_dim1 = torch.stack([x, x, x, x], dim = 1)
x_stack_dim1

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [95]:
# torch.squeeze() - removel all single dimentions from a target tensor
print(f'Previous shape: {x_reshape.shape}')
print(f'Previous data: {x_reshape}')
print('-' * 50)
x_reshape_squeeze = torch.squeeze(x_reshape)
print(f'New shape: {x_reshape_squeeze.shape}')
print(f'New data: {x_reshape_squeeze}')

Previous shape: torch.Size([1, 10])
Previous data: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
--------------------------------------------------
New shape: torch.Size([10])
New data: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [96]:
# torch.unsequeeze() - add a dimension of 1 to a target tensor at a specified dimention
print(f'Previous targe: {x_reshape_squeeze}')
print(f'Previous shape: {x_reshape_squeeze.shape}')

# Add extra dimension to tensor
print('-' * 50)
x_unsqueeze_dim0 = torch.unsqueeze(x_reshape_squeeze, dim = 0)
print(f'New target dim 0: {x_unsqueeze_dim0}')
print(f'New shape dim 0: {x_unsqueeze_dim0.shape}')
print('-' * 50)
x_unsqueeze_dim1 = torch.unsqueeze(x_reshape_squeeze, dim = 1)
print(f'New target dim 1: {x_unsqueeze_dim1}')
print(f'New shape dim 1: {x_unsqueeze_dim1.shape}')

Previous targe: tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previous shape: torch.Size([10])
--------------------------------------------------
New target dim 0: tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
New shape dim 0: torch.Size([1, 10])
--------------------------------------------------
New target dim 1: tensor([[ 5.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])
New shape dim 1: torch.Size([10, 1])


In [112]:
# Torch.permute() - rearrange the dimensions of a tensor (เรียงลำดับของมิติใหม่) 
x_original = torch.rand(size = (224, 224, 3))
print('-' * 50)
print(f'Before permuted: {x_original.shape}')

# Permute the original tensor to rearrange the dimensions
print('-' * 50)
x_permuted = x_original.permute(2, 0, 1)
print(f'Shape after permuted: {x_permuted.shape}')

--------------------------------------------------
Before permuted: torch.Size([224, 224, 3])
--------------------------------------------------
Shape after permuted: torch.Size([3, 224, 224])
